### ISSUE TITLE
404 на ссылках ассетов с доменом сайта 

### ISSUE THREAD

**Issue by alex-rd** [brainmurder/insales-uploader#10]
Insales со вчерашнего дня отдает 404 при ссылках с доменом сайта.
Соответственно скачивание темы на локальный компьютер невозможна.

**Comment by VladimirIvanin** [comment]
Добрый день!

Сегодня проверял скачивание, работает.

Видимо cdn был временно недоступен

**Comment by alex-rd** [comment]
Сообщение об "insales со вчерашнего дня отдает 404 при ссылках с доменом сайта."
Я немного неправильно сформулировал.
О том, что так теперь будет прислала тех.поддержка Insales, часть сообщения:

"Срочная новость!
С сегодняшнего дня мы начнём отдавать ошибки 404 при запросе файлов темы через домен магазина. "

И ассеты не скачиваются (идет 404 ошибка).
Любые .liquid файлы скачиваются, остальные нет

**Comment by VladimirIvanin** [comment]
Добавил фикс на урлы в 0.27.2

**Comment by alex-rd** [comment]
домен assets.insales.ru, будет в дальнейшем рабочим для тем, у которых файлы лежат на assets3.insales.ru (или assets и assets3 это просто сервера cdn и запрос можно делать к любому)?

**Comment by VladimirIvanin** [comment]
Сделал запрос, чтоб в ответе апи был домен ассета. 
Фикс который я сделал ненадежен, домены могут меняться, но пока хоть так(
Спасибо за обратную связь!

**Comment by alex-rd** [comment]
Может вынести в настройки и адрес сервера, на котором лежат файлы (если не определен, то подставлять что-то по-умолчанию).
Адрес можно всегда посмотреть на сайте, который в работе. (в качестве временной меры поможет)

**Comment by VladimirIvanin** [comment]
![image](https://user-images.githubusercontent.com/15268753/33508519-dc222ccc-d70b-11e7-9d06-69ccdad142e0.png)

Добавил настройку в v0.27.3
