### ISSUE TITLE
Метод upload

### ISSUE THREAD

**Issue by diproart** [brainmurder/insales-uploader#2]
Было бы здорово добавить метод "принудительной" загрузки на сервер. Есть метод `download`, но нет метода `upload`, только `stream`.

``` javascript
var InsalesUploader = require('insales-uploader');
// InsalesUploader.upload(<overwrite|update>);
InsalesUploader.upload(true);
```

**Comment by VladimirIvanin** [comment]
Привет!
Я планировал сделать push/pull как альтернативу upload/download.
push будет приводить тему на сервере к виду локальной версии, pull наоборот.
Upload сделаю.

**Comment by VladimirIvanin** [comment]
Upload добавил, но пока в сыром виде. (0.19.3)
Метод принимает параметр `update: true/false`.
Если true то совпадающие файлы будут обновляться на сервере, иначе файл не заливается.

**Comment by diproart** [comment]
Сейчас использую `git` для отслеживания изменений при слиянии изменений локальной версии и версии сервера. Есть ли какие либо рекомендации. pullTheme, pushTheme перезаписывают, нужна ли для `upload`, `download` возможность работы только с измененными файлами, например загрузка только более новых файлов с сервера. Пример простой, менеджер меняет "конфиг" темы, а разработка в процессе, нужно загрузить только файлы, которые изменили  (сейчас это через git).

НЕ могу понять нужно это или нет, вроде git все решает.

**Comment by VladimirIvanin** [comment]
Пока не решил проблему сравнения файлов на сервере и в локальной версии. Посмотрю можно ли сравнить по дате последнего изменения, но вот по байтам не прокатило сравнить, а инфы о контрольной сумме с сервера не прилетает. 
Единственное, что сравниваю это просто список файлов.
Возможно, что то изменится если в ответ сервера добавят контрольную сумму или добавят метод для скачивания темы архивом. 
Как вариант сделаю метод который скачает тему во временную папку и сравнит с локальной версией.
pushTheme к сожалению пока работает не стабильно(

**Comment by VladimirIvanin** [comment]
Реализован метод `pullTheme`.
