### ISSUE TITLE
Документация, структура проекта

### ISSUE THREAD

**Issue by diproart** [brainmurder/insales-uploader#3]
Необходимо пояснение к структуре проекта и логике работы
- assets/  ? 
- media/ ?

или
- assets/js/cart.js 
- media/cart.js

в [официальной документации](http://www.insales.ru/collection/basics) нет директории `/assets`, 
что вызывает резонный вопрос - в какой директории править файлы? И в `/assets/` также есть `media`. Считаю, что нужно добавить в документацию пояснения (или ссылки на оф. вики) по структуре и назначению директорий. Пояснение логики обработки файлов  `insales-uploader`'ом было бы кстати. Это сделает начало работы с проектом более быстрым.

Спасибо за Вашу работу.

**Comment by VladimirIvanin** [comment]
Assets сделал для удобства, на платформе ассеты никогда не будут разбираться на категории, именно когда архив с темой скачиваем или закачиваем.
Чтоб поддерживать архитектуру решил синхронизировать эти две папки. Если включить стрим и отредактировать файл в одном или другом месте, изменения продублируются в локальных папках.
Но папка media всегда главная, uploader на неё ориентируется.
Насчет документации и вообще пояснения вот этой каши, добавлю в readme почему так.
А в целом когда дойду до стабильной версии то запишу видео как с ним работать.

Спасибо за обратную связь!
