### ISSUE TITLE
Вопрос по settings_data.json

### ISSUE THREAD

**Issue by diproart** [brainmurder/insales-uploader#4]
Появились новые параметры

```
{
...
 "remote_theme_id": 999,
 "source_account_id": null,
 "theme_title": "Имя темы"
}
```

они имеют отношение к **insales-uploader** или это все про платформу?

**Comment by VladimirIvanin** [comment]
settings_data.json полезен только для подключения js фреймворка - http://liquidhub.ru/collection/start 

"remote_theme_id", "source_account_id" - эти свойства задаются платформой, их трогать не стоит

"theme_title" - это просто название темы в бэк-офисе
