### ISSUE TITLE
Компиляция sass

### ISSUE THREAD

**Issue by diproart** [brainmurder/insales-uploader#5]
Сейчас файлы `css` и `sass` живут вместе, одни через `//= require`, другие через `@import`. 
Если не трудно поясните логику работу платформы, темы со стилями. Я так понял платформа собирает ассеты и отправляет на CDN.

Хочу оставить, только несколько файлов для кастомизации стилей через редактор, остальные собирать в `bundle`. У пользователя будет возможность создавать свои стили, но не править "стили темы" (типа "core") . Да, это по-другому, то есть будут пустые файлы, типа custom, collection  и т.д., бандл компилируется локально, uploader "забрасывает" его на сервер. 

Если вопрос "не туда" заранее извиняюсь.

**Comment by VladimirIvanin** [comment]
Всё кроме сниппетов и шаблонов живет на CDN. 
scss и js можно склеивать с помощью дерективы `#= require`, внутренний сборщик просто склеивает файлы в один. 
Scss лучше склеивать через родной `@import`.
В  основном в разработке используются scss, чтоб можно было задавать цвета из settings.html.
Сейчас реализован проброс переменных из сеттингов через scss файл `@import "settings"`, как этим пользоваться буду рассказывать тут http://liquidhub.ru/, как будет информация сюда скину ссылку.
А собирать `bundle` локально или на платформе личное дело, но сборка на платформе конечно дольше чем в локальном сборщике.
