### ISSUE TITLE
настройка "exclude"

### ISSUE THREAD

**Issue by diproart** [brainmurder/insales-uploader#6]
Стандартная возможность для многих скриптов и утилит - это указание исключений.
Есть файлы, которые "мешают", создают ненужные трудности в работе с git. Можно исключить их в `.gitignore`, но собственный механизм исключений не будет лишним для  `insales-uploader`.

К примеру: 
```
// может относительно 
// корня темы
{
  "exclude": [
     "assets/js/jquery.min.js",
     "assets/js/swiper.min.js",
     "assets/js/jquery.min.js",
     "media/*.min.js"
   ]
}
```
или что-то подобное, было бы кстати.

**Comment by VladimirIvanin** [comment]
А что будет делать `exclude` в `insales-uploader`?
Указанные файлы или папки будут полностью игнорироваться или например только отслеживание изменений.
В каком кейсе мешают файлы?
На сколько я могу догадаться эти файлы прилетают в media через сборщик и uploader делает лишние операции по отправке библиотек.

**Comment by diproart** [comment]
файлы будут полностью игнорироваться 

Например:
- файл настройки темы: `config/settings_data.json`
- минифицированные версии библиотек `*.min.js`
- некоторые из сниппетов и шаблонов
- возможно файлы агрегаторы

Все это "вокруг" одновременной работы нескольких разработчиков и менеджеров с одной темой, а также более простого слияния изменений.

Файлы не мешают, это **физическая защита некоторых файлов** от случайной перезаписи, с сохранением высокого уровня интерактивности, уменьшение конфликтов при совместной работе.

**Comment by VladimirIvanin** [comment]
Сделаю игнорирование только для стрима файлов. Но это можно сделать и сейчас, если использовать gulp-watch:

```
var gulp = require('gulp');
var insalesUp = require('insales-uploader');
var watch = require('gulp-watch');

gulp.task('watch', function(){
  return watch(InsalesUploader.paths.toWatch, { ignored: '*.min.js'}, function (_vinyl) {
    InsalesUploader.triggerFile(_vinyl.event, _vinyl.path);
  });
});
```

Не проверял, но скорее всего сработает
