### ISSUE TITLE
Пути к изображениям при загрузке

### ISSUE THREAD

**Issue by diproart** [brainmurder/insales-uploader#7]
Есть ли способ обращения к файлам изображений напрямую по простым ссылкам или как-нибудь еще?

Пример:
Есть фоновое изображение (например фон страницы или элемента). При локальной разработке файл помещается в `assets/img`, **insales-uploader** помещает его в `media` и синхронизирует с сервером. 

```css
.bar {
  background-image: url( "__which-link-to-my-pictures__/image.png");
}
```

Вопрос: как узнать ссылку на загруженный файл? или только `url.gif | assets_url`. Или есть еще варианты работы с файлами? Какие есть рекомендации?

При загрузке ссылки будут типа `https://static-eu.insales.ru/files/1/2746/2271930/original/slide1.jpg`, но узнать их можно только "физически ткнув"  в файл. Варианты?

p.s. Сейчас используем свой CDN или proxy на этапе верстки, так проще при разработке, но при переносе и обновлении это уже труднее, или оставлять у себя все файлы, относящиеся к стилю и дизайну.

**Comment by VladimirIvanin** [comment]
Обращение к картинкам в css без assets_url, происходит просто указав:
```
.bar {
  background-image: url( "image.png");
}
```
Css, картинки и вообще вся медиа лежит в одной папке, потому путь от корня.

**Comment by VladimirIvanin** [comment]
Если я верстаю статику для интеграции в инсейлс, то настраиваю сборщик так, что все файлы на выходе лежат в одной папке. В таком случае не приходтся адаптировать css.

**Comment by diproart** [comment]
Спасибо за разъяснения, все понятно.

---

Прошу прощение за настойчивость,
то есть "image.png", размещенный в `media`, в `css` это `url("image.png")` 

В инлайн стилях в html?
`<div style="background-image: url('image.png'); width: 240px; height: auto;">`.

А доступ напрямую через `http` - `<img src="<что то там>/image.png">`?
К примеру `<мой магазин>/image.png` или только CDN,
сейчас это `https://assets3.insales.ru/assets/1/7754/704074/v_1484571960/build/no_image.png`

p.s. Пытаемся создать правила работы с использованием **uploader**, что надо делать, что нет.

**Comment by VladimirIvanin** [comment]
В сниппетах и шаблонах все таки нужно писать фильтр asset_url. cdn я так понимаю может меняться, точнее я мало, что знаю о работе бекенда. 
По поводу игнора файлов, руки не доходят новую версию дописать. с возможностью настройки.
для себя и не только начал вести сниппеты:
https://atom.io/packages/insales-liquid-snippets
Пока только для атома, но надо сделать сборщик для других редакторов, если есть идеи, что перенести в сниппеты, буду рад идеям.
Вы в каком редакторе/IDE работаете?

**Comment by VladimirIvanin** [comment]
https://github.com/VladimirIvanin/insales-liquid-snippets/tree/master/snippets
тут исходники сниппетов

**Comment by diproart** [comment]
Два основных для frontend - WebStorm, Visual Studio Code
