### ISSUE TITLE
Error: Cannot find module 'esLint'

### ISSUE THREAD

**Issue by diproart** [brainmurder/insales-uploader#8]
+ os: Ubuntu 16.04.2 LTS
+ insales-uploader: 0.26.2

```
var esLinter = require("esLint").linter;
```

https://github.com/VladimirIvanin/insales-uploader/blob/ddfffe389215555a4a6efc45c7a77fa2da24109b/lib/file-system/watch.js#L9

Проблема в **camelCase** - `esLint`, должно быть `eslint`

**Comment by VladimirIvanin** [comment]
Поправил! 
Спасибо!
